#!/usr/bin/env python3
"""Shim that gives test_site.py the same module-level interface as an instance's build_site,
but calls engine/build.py with the synthetic fixture content.

Interface contract (must stay compatible with an instance's build_site interface):
  - OUT              : Path — set by the test before calling build()
  - SITE_CONFIG      : dict — the synthetic site identity (test parameterises from this)
  - build(site_url)  : calls engine.build.build() with fixture content + synthetic site identity
  - load_json(rel)   : reads JSON from fixture_content/<rel>
  - work_slug        : re-exported from engine.build

The test sets:
    import engine_build as build_site
    build_site.OUT = TMP
    build_site.build(SITE_URL)
    build_site.load_json("gallery/gallery_data.json")
"""
import json
import sys
from pathlib import Path

# engine/ → on sys.path so we can import build.py as a module
_ENGINE_ROOT = Path(__file__).resolve().parent.parent   # exhibition-engine/
sys.path.insert(0, str(_ENGINE_ROOT / "engine"))
import build as _engine   # noqa: E402 — engine/build.py

# Fixture content generated by make_synthetic.py
FIXTURE = Path(__file__).resolve().parent / "fixture_content"

# Synthetic site identity — the test parameterises copyright checks from this
SITE_CONFIG = {
    "site_name":        "SYNTH EXHIBITION",
    "creator":          "Synth Author",
    "root_title":       "SYNTH EXHIBITION — Synth Author",
    "root_description": "A synthetic exhibition for engine testing. Tap any work to walk.",
    "collection_name":  "SYNTH EXHIBITION — the exhibition",
}

# Set by the test before calling build()
OUT = None

# Re-export the slug helper the test uses directly
work_slug = _engine.work_slug
# Re-export the EX-LADDER helpers (INV-63) the ladder test uses directly
srcset_of = _engine.srcset_of
tier_url = _engine.tier_url
# Re-export the display-cap + watermark helper (test_site.py INV-56 row accesses it directly)
_copy_assets_capped = _engine._copy_assets_capped


def load_json(relpath):
    """Read JSON from the fixture content dir — mirrors build_site.load_json interface."""
    with open(FIXTURE / relpath, encoding="utf-8") as fh:
        return json.load(fh)


def build(site_url, ga_id="", enable=None, display_max=None):
    """Bake the synthetic fixture into OUT.  The caller must set OUT first.
    display_max caps the served images + writes the EX-LADDER tiers (needs Pillow)."""
    engine_assets = _ENGINE_ROOT / "engine" / "assets"
    inst_assets = FIXTURE / "instance-assets"
    return _engine.build(
        site_url,
        ga_id=ga_id,
        enable=enable or [],
        content_dir=FIXTURE,
        out_dir=OUT,
        engine_assets_dir=engine_assets,
        instance_assets_dir=inst_assets if inst_assets.exists() else None,
        site_config=SITE_CONFIG,
        display_max=display_max,
    )
